import express, { Express } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import faqRoutes from '../modules/faq/faq.routes.js';
import communityRoutes from '../modules/community/community.routes.js';
import searchRoutes from '../modules/search/search.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import adminAuditRoutes from '../modules/admin/admin-audit.routes.js';
import adminAutoAnswerRoutes from '../modules/admin/admin-auto-answer.routes.js';
import analyticsRoutes from '../modules/search/analytics.routes.js';
import notificationRoutes from '../modules/notification/notification.routes.js';
import teaRoutes from '../modules/notification/tea.routes.js';
import reputationRoutes from '../modules/moderation/reputation.routes.js';
import moderationRoutes from '../modules/moderation/moderation.routes.js';
import zoomRoutes from '../modules/zoom/zoom.routes.js';
import knowledgeRoutes from '../modules/knowledge/knowledge.routes.js';
import askAiRoutes from '../modules/ai/ask-ai.routes.js';
import uploadRoutes from '../modules/upload/upload.routes.js';
import publicFaqRoutes from '../modules/faq/public-faq.routes.js';
import batchRoutes from '../modules/program/batch.routes.js';
import programRoutes from '../modules/program/program.routes.js';
import adminProgramSettingsRoutes from '../modules/program/admin-program-settings.routes.js';
import programZoomRoutes from '../modules/program/program-zoom.routes.js';
import programDiscordRoutes from '../modules/program/program-discord.routes.js';
import programFeatureFlagsRoutes from '../modules/program/program-feature-flags.routes.js';
import programAppSettingsRoutes from '../modules/program/program-app-settings.routes.js';
import courseRoutes from '../modules/program/course.routes.js';
import enrollmentRoutes from '../modules/program/enrollment.routes.js';
import supportRoutes from '../modules/support/support.routes.js';
import featureFlagRoutes from '../modules/program/feature-flag.routes.js';
import adminConfigRoutes from '../modules/admin/admin.config.routes.js';
import { documentRouter, documentAdminRouter } from '../modules/knowledge/documents.routes.js';
import welcomeRoutes from '../modules/program/welcome.routes.js';
import adminWelcomeRoutes from '../modules/admin/admin-welcome.routes.js';
import adminMentorRoutes from '../modules/admin/admin-mentor.routes.js';
import adminTimelineRoutes from '../modules/admin/admin-timeline.routes.js';
import { adminRouter as appSettingsAdminRouter, publicRouter as appSettingsPublicRouter } from '../modules/program/app-settings.routes.js';
import registrationControlRoutes from '../modules/program/registration-control.routes.js';
import adminCategoryClusterRoutes from '../modules/program/admin-category-cluster.routes.js';
import publicCategoryClusterRoutes from '../modules/program/public-category-cluster.routes.js';
import healthRoutes from '../modules/health/health.routes.js';

export function registerRoutes(app: Express): void {
  const router = express.Router();

  router.use('/auth', authRoutes);
  router.use('/faq', faqRoutes);
  router.use('/community', communityRoutes);
  router.use('/search', searchRoutes);
  router.use('/admin', adminRoutes);
  router.use('/admin', adminAutoAnswerRoutes);
  router.use('/admin', adminAuditRoutes);
  router.use('/reputation', reputationRoutes);
  router.use('/moderation', moderationRoutes);
  router.use('/analytics', analyticsRoutes);
  router.use('/notifications', notificationRoutes);
  router.use('/notifications/tea', teaRoutes);
  router.use('/zoom', zoomRoutes);
  router.use('/knowledge', knowledgeRoutes);
  router.use('/ask-ai', askAiRoutes);
  router.use('/upload', uploadRoutes);
  router.use('/public', publicFaqRoutes);
  router.use('/health', healthRoutes);
  router.use('/batches', batchRoutes);
  router.use('/programs', programRoutes);
  router.use('/admin/programs', adminProgramSettingsRoutes);
  router.use('/admin/programs', programZoomRoutes);
  router.use('/admin/programs', programDiscordRoutes);
  router.use('/admin/programs', programFeatureFlagsRoutes);
  router.use('/admin/programs', programAppSettingsRoutes);
  router.use('/admin/programs/:batchId/category-clusters', adminCategoryClusterRoutes);
  router.use('/public/category-clusters', publicCategoryClusterRoutes);
  router.use('/courses', courseRoutes);
  router.use('/', enrollmentRoutes);
  router.use('/support', supportRoutes);
  router.use('/feature-flags', featureFlagRoutes);
  router.use('/admin/config', adminConfigRoutes);
  router.use('/documents',       documentRouter);
  router.use('/admin/documents', documentAdminRouter);
  router.use('/welcome', welcomeRoutes);
  router.use('/admin/welcome', adminWelcomeRoutes);
  router.use('/admin/mentors', adminMentorRoutes);
  router.use('/admin/timeline-steps', adminTimelineRoutes);
  router.use('/admin/settings',  appSettingsAdminRouter);
  router.use('/public/settings', appSettingsPublicRouter);
  router.use('/admin/registration-config', registrationControlRoutes);

  app.use('/csfaq/api', router);
}
