#!/bin/bash
# ============================================================
# Yaksha FAQ Portal — Full Stack Runner (with env setup)
#
# Tags: [ALERT] = red+bold, [INFO] = blue, [OK] = green, [WARN] = yellow
# Mirrors the backend logger so you can grep your way through.
#
# Usage: ./run.sh
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR"
BACKEND="$ROOT/apps/backend"
FRONTEND="$ROOT/apps/frontend"

# ── Terminal colors (ANSI) ───────────────────────────────────────────────────
# Use bash ANSI-C quoting ($'...') so the values hold the
# literal ESC byte (0x1b). Plain "..." would keep "\033" as
# the 4-char text — sed then writes that text to the terminal
# verbatim instead of an escape sequence, and the user
# sees "033[2m" instead of dim color.
F_INFO=$'\033[94m'
F_OK=$'\033[92m'
F_WARN=$'\033[93m'
F_ALERT=$'\033[1;31m'
F_DIM=$'\033[2m'
F_BOLD=$'\033[1m'
F_RESET=$'\033[0m'

# ── Tagged log helpers ──────────────────────────────────────────────────────
log()   { echo -e "${F_INFO}[INFO]${F_RESET} $1"; }
ok()    { echo -e "${F_OK}[OK]${F_RESET}   $1"; }
warn()  { echo -e "${F_WARN}[WARN]${F_RESET} $1"; }
alert() { echo -e "${F_ALERT}[ALERT]${F_RESET} $1"; }
dim()   { echo -e "${F_DIM}       $1${F_RESET}"; }
die()   { alert "$1" >&2; exit 1; }

NGROK_PID=""
FRONTEND_PID=""

cleanup() {
  echo ""
  alert "shutdown initiated — signal received"
  [ -z "$BACKEND_PID" ] && [ -f /tmp/yaksha-backend.pid ] && BACKEND_PID=$(cat /tmp/yaksha-backend.pid)
  [ -n "$BACKEND_PID" ] && kill $BACKEND_PID 2>/dev/null || true
  [ -n "$FRONTEND_PID" ] && kill $FRONTEND_PID 2>/dev/null || true
  [ -n "$NGROK_PID" ] && kill $NGROK_PID 2>/dev/null || true
  pkill -f "tsx.*server" 2>/dev/null || true
  rm -f /tmp/yaksha-backend.pid
  ok "shutdown complete"
  exit 0
}
trap cleanup SIGINT SIGTERM

# ── Ensure .env exists ────────────────────────────────────────────────────────
ensure_env() {
  local env_file="$BACKEND/.env"
  if [ ! -f "$env_file" ]; then
    if [ -f "$BACKEND/.env.example" ]; then
      log "creating .env from .env.example"
      cp "$BACKEND/.env.example" "$env_file"
    else
      touch "$env_file"
    fi
  fi
}

# ── Read a var from .env (returns empty if not set) ───────────────────────────
read_env() {
  local var_name=$1
  grep "^${var_name}=" "$BACKEND/.env" 2>/dev/null | head -1 | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g"
}

# ── Write a var to .env.local ──────────────────────────────────────────────────
write_env_local() {
  local var_name=$1
  local value=$2
  local local_file="$BACKEND/.env.local"
  # Remove existing entry
  grep -v "^${var_name}=" "$local_file" 2>/dev/null > "$local_file.tmp" || true
  mv "$local_file.tmp" "$local_file"
  # Append new entry
  echo "${var_name}=${value}" >> "$local_file"
}

# ── Prompt user for a value if not in .env ───────────────────────────────────
prompt_if_missing() {
  local var_name=$1
  local description=$2
  local current
  current=$(read_env "$var_name")
  [ -n "$current" ] && current=$(grep "^${var_name}=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
  [ -n "$current" ] && return 0

  echo ""
  echo -e "${F_WARN}[WARN]${F_RESET} missing: ${F_BOLD}${var_name}${F_RESET}"
  echo -e "  $description"
  echo -n "  Enter value: "
  read -r value
  if [ -z "$value" ]; then
    die "${var_name} is required — cannot continue"
  fi
  write_env_local "$var_name" "$value"
  ok "saved ${var_name}"
}

# ── Optional var prompt ────────────────────────────────────────────────────────
prompt_optional() {
  local var_name=$1
  local description=$2
  local current
  current=$(grep "^${var_name}=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
  [ -n "$current" ] && return 0

  echo ""
  echo -e "  ${F_DIM}${description}${F_RESET}"
  echo -n "  Enter value (or press Enter to skip): "
  read -r value
  [ -n "$value" ] && write_env_local "$var_name" "$value" && ok "saved ${var_name}"
}

# ── Setup env vars ─────────────────────────────────────────────────────────────
setup_env() {
  ensure_env

  # Create .env.local if it doesn't exist
  local local_file="$BACKEND/.env.local"
  if [ ! -f "$local_file" ]; then
    {
      echo "# Local env overrides — generated by run.sh"
      echo "# This file is NOT committed to git"
      echo ""
    } > "$local_file"
  fi

  # ── Fast path: skip prompts if ALL required vars are already in .env or .env.local ──
  local required_vars="MONGODB_URI JWT_SECRET"
  local all_set=true
  for var in $required_vars; do
    local val_in_env=$(grep "^${var}=" "$BACKEND/.env" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
    local val_in_local=$(grep "^${var}=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
    if [ -z "$val_in_env" ] && [ -z "$val_in_local" ]; then
      all_set=false
      break
    fi
  done

  if [ "$all_set" = true ]; then
    echo ""
    ok "all required env vars found in .env / .env.local — skipping prompts"
    echo ""
    return 0
  fi

  echo ""
  echo "=============================================="
  echo "  Yaksha FAQ Portal — Env Setup"
  echo "=============================================="

  prompt_if_missing "MONGODB_URI" "MongoDB Atlas connection string"
  prompt_if_missing "JWT_SECRET"    "JWT secret — run: openssl rand -hex 32"

  echo ""
  echo "  --- Optional (press Enter to skip) ---"
  prompt_optional "MINIMAX_API_KEY"     "MINIMAX_API_KEY (for Zoom transcript extraction)"
  prompt_optional "NGROK_AUTH_TOKEN"    "NGROK_AUTH_TOKEN (from ngrok.com dashboard — enables webhook tunnel)"
  prompt_optional "ZOOM_CLIENT_ID"      "ZOOM_CLIENT_ID (from Zoom App marketplace)"
  prompt_optional "ZOOM_CLIENT_SECRET"  "ZOOM_CLIENT_SECRET (from Zoom App marketplace)"
  prompt_optional "REDIS_URL"           "REDIS_URL (Upstash Redis — enables cross-instance cache)"
  prompt_optional "REDIS_TOKEN"         "REDIS_TOKEN (Upstash REST API token)"
  prompt_optional "REDIS_TCP_URL"       "REDIS_TCP_URL (BullMQ TCP — enables OCR / document pipeline)"
  prompt_optional "SENTRY_DSN"          "SENTRY_DSN (Sentry error tracking DSN)"
  prompt_optional "DISCORD_WEBHOOK_URL" "DISCORD_WEBHOOK_URL (channel webhook — ALERTs ping Discord when set)"

  echo ""
  ok "env setup complete — saved to .env.local"
}

# ── Wait for backend ─────────────────────────────────────────────────────────────
wait_for_backend() {
  local max_wait=20
  local waited=0
  log "waiting for backend to be ready..."
  while [ $waited -lt $max_wait ]; do
    local status
    status=$(curl -sf -o /dev/null -w "%{http_code}" --max-time 2 http://localhost:6767/csfaq/api/health || echo "000")
    if [ "$status" = "200" ]; then
      ok "backend ready"
      return 0
    fi
    sleep 2
    waited=$((waited + 2))
    echo -n "."
  done
  warn "backend not ready after ${max_wait}s — continuing anyway"
}

# ── Start backend ──────────────────────────────────────────────────────────────
start_backend() {
  log "starting backend..."
  cd "$BACKEND"
  set -a
  source ".env" 2>/dev/null || true
  source ".env.local" 2>/dev/null || true
  set +a
  # Kill any existing process on port 6767 before starting
  pkill -f "tsx.*server" 2>/dev/null || true
  sleep 1

  # Session log — timestamped, previous sessions preserved
  SESSION_TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
  SESSION_LOG="$ROOT/logs/session_${SESSION_TIMESTAMP}.txt"
  mkdir -p "$ROOT/logs"
  touch "$SESSION_LOG"
  echo "$SESSION_LOG" > /tmp/yaksha-session-log

  # Run tsx — prefix each line with [backend] dim tag for greppable scrollback.
  ../../node_modules/.bin/tsx watch src/server.ts 2>&1 | \
    sed -u "s/^\([^[]]*\)/${F_DIM}[backend]${F_RESET} \1/" | \
    tee "$SESSION_LOG" &
  BACKEND_PID=$!
  echo $BACKEND_PID > /tmp/yaksha-backend.pid
  ok "backend pid $BACKEND_PID — log: $SESSION_LOG"

  if [ -n "$DISCORD_WEBHOOK_URL" ] && [ "$DISCORD_WEBHOOK_URL" != "###" ]; then
    ok "discord webhook configured — ALERTs will ping your channel"
  else
    dim "discord webhook not configured (DISCORD_WEBHOOK_URL=###) — ALERTs only hit console"
  fi
}

# ── Start ngrok (tunnel to expose local backend for Zoom webhook) ──────────────
start_ngrok() {
  local ngrok_token=$(grep "^NGROK_AUTH_TOKEN=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
  if [ -z "$ngrok_token" ]; then
    dim "NGROK_AUTH_TOKEN not set — skipping ngrok tunnel"
    return 0
  fi

  log "starting ngrok tunnel to port 6767..."
  ngrok config add-authtoken "$ngrok_token" 2>/dev/null || true
  ngrok http 6767 --log=stdout > /tmp/ngrok.log 2>&1 &
  NGROK_PID=$!
  sleep 4

  # Extract the HTTPS URL
  local ngrok_url=$(grep -o 'https://[a-zA-Z0-9-]*\.ngrok-free\.app' /tmp/ngrok.log 2>/dev/null | head -1 || true)
  if [ -n "$ngrok_url" ]; then
    ok "ngrok tunnel: $ngrok_url"
    # Update ZOOM_REDIRECT_URI in .env.local if it has the old ngrok URL
    local old_url=$(grep "^ZOOM_REDIRECT_URI=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
    if [ -n "$old_url" ]; then
      sed -i '' "s|^ZOOM_REDIRECT_URI=.*|ZOOM_REDIRECT_URI=${ngrok_url}/api/zoom/auth/callback|" "$BACKEND/.env.local"
      ok "updated ZOOM_REDIRECT_URI → ${ngrok_url}/api/zoom/auth/callback"
    fi
  else
    warn "could not detect ngrok URL — check /tmp/ngrok.log"
  fi
}

# ── Start frontend ──────────────────────────────────────────────────────────────
start_frontend() {
  log "starting frontend..."
  cd "$FRONTEND"

  # Reuse the same session log file that backend started
  SESSION_LOG=$(cat /tmp/yaksha-session-log 2>/dev/null || echo "")
  if [ -z "$SESSION_LOG" ]; then
    SESSION_LOG="$ROOT/logs/session_$(date '+%Y-%m-%d_%H-%M-%S').txt"
    mkdir -p "$ROOT/logs"
    touch "$SESSION_LOG"
  fi

  # Run vite — prefix with [frontend] dim tag, append to session log
  npx pnpm@9 run dev 2>&1 | \
    sed -u "s/^\([^[]]*\)/${F_DIM}[frontend]${F_RESET} \1/" | \
    tee -a "$SESSION_LOG" &
  FRONTEND_PID=$!
  ok "frontend pid $FRONTEND_PID — log: $SESSION_LOG"
}

# ── Kill existing processes ──────────────────────────────────────────────────────
kill_existing() {
  local killed=0
  for port in 5173 6767; do
    local pid=$(lsof -ti:$port 2>/dev/null || true)
    if [ -n "$pid" ]; then
      warn "killing existing process on port $port (pid $pid)"
      kill -9 $pid 2>/dev/null || true
      killed=1
    fi
  done
  [ $killed -eq 1 ] && sleep 1 && ok "cleared"
}

check_url_alive() {
  curl -sf --max-time 2 http://localhost:5173 > /dev/null 2>&1
}

# ── Check for remote updates on current branch ────────────────────────────────
check_for_updates() {
  # Skip if not in a git repo
  if ! git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    return 0
  fi

  cd "$ROOT"

  # Get current branch
  local current_branch
  current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
  if [ -z "$current_branch" ] || [ "$current_branch" = "HEAD" ]; then
    dim "not on a named branch — skipping update check"
    return 0
  fi

  # Check upstream tracking branch exists
  local upstream
  upstream=$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2>/dev/null || true)
  if [ -z "$upstream" ]; then
    dim "branch '$current_branch' has no upstream tracking — skipping update check"
    return 0
  fi

  log "checking for updates on $current_branch..."

  # Fetch silently to update remote refs
  if ! git fetch --quiet 2>/dev/null; then
    warn "could not fetch from remote — skipping update check"
    return 0
  fi

  # Count commits ahead/behind
  local ahead behind
  ahead=$(git rev-list --count "${upstream}..HEAD" 2>/dev/null || echo 0)
  behind=$(git rev-list --count "HEAD..${upstream}" 2>/dev/null || echo 0)

  # Nothing new on remote
  if [ "$behind" -eq 0 ]; then
    if [ "$ahead" -eq 0 ]; then
      ok "branch '$current_branch' is up to date with $upstream"
    else
      dim "no new commits on $upstream ($ahead local commit(s) ahead)"
    fi
    return 0
  fi

  echo ""
  warn "$behind new commit(s) available on $upstream"
  dim "your local branch is behind by $behind commit(s):"
  git log --oneline "HEAD..${upstream}" 2>/dev/null | head -5 | sed "s/^/${F_DIM}    ${F_RESET}/"
  [ "$behind" -gt 5 ] && dim "    ... and $((behind - 5)) more"

  # Warn if there are uncommitted local changes
  if ! git diff --quiet HEAD 2>/dev/null || ! git diff --cached --quiet HEAD 2>/dev/null; then
    warn "you have uncommitted local changes — pull may conflict"
  fi

  echo ""
  echo -n "  Pull latest changes from '$upstream'? [y/N] (auto-skip in 7s): "
  if read -t 7 -r reply; then
    : # got a reply within timeout
  else
    echo ""
    dim "no response in 7s — skipping pull"
    return 0
  fi
  case "$reply" in
    [yY]|[yY][eE][sS])
      log "pulling from $upstream..."
      if git pull 2>&1 | sed "s/^/${F_DIM}    ${F_RESET}/"; then
        ok "pull complete"
      else
        warn "pull failed — resolve conflicts manually before starting servers"
        return 0
      fi
      ;;
    *)
      dim "skipped — continuing with local state"
      ;;
  esac
  echo ""
}

# ── Read a var from .env or .env.local ────────────────────────────────────────
read_env_with_local() {
  local var_name=$1
  local val
  val=$(grep "^${var_name}=" "$BACKEND/.env.local" 2>/dev/null | head -1 | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g" || echo "")
  if [ -z "$val" ]; then
    val=$(grep "^${var_name}=" "$BACKEND/.env" 2>/dev/null | head -1 | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g" || echo "")
  fi
  echo "$val"
}

# ── Check GCS credentials and connection ─────────────────────────────────────
check_gcs_connection() {
  local bucket
  bucket=$(read_env_with_local "GCS_BUCKET")
  if [ -z "$bucket" ] || [[ "$bucket" == dummy* ]]; then
    dim "GCS is not configured or using dummy bucket ($bucket) — skipping GCS network check"
    return 0
  fi

  log "verifying GCS connection..."
  if (cd "$BACKEND" && npx tsx src/scripts/testGcsConnection.ts >/tmp/gcs-test.log 2>&1); then
    ok "GCS connection check passed successfully"
  else
    warn "GCS connection check failed. Image uploads may 503."
    dim "Check /tmp/gcs-test.log for full details."
  fi
}

# ── Main ───────────────────────────────────────────────────────────────────────
echo ""
check_for_updates
echo ""
alert "Yaksha FAQ Portal — full stack runner"
echo ""

setup_env
check_gcs_connection

if check_url_alive; then
  warn "frontend already live on 5173 — clearing ports"
  kill_existing
else
  ok "port 5173 is free"
fi

start_ngrok
start_backend
wait_for_backend
start_frontend

echo ""
ok "backend  →  http://localhost:6767"
ok "frontend →  http://localhost:5173"
echo ""
dim "press Ctrl+C to stop (ALERT will fire to Discord if configured)"
echo ""

wait
