/**
 * CategoryCluster — Dynamic Categories feature (v1.70)
 *
 * Per-program clustering of FAQ `category` strings. The clusterer runs
 * every 24h (see utils/ai/categoryClusterer.ts) and groups similar
 * categories together using dot-product similarity on FAQ embeddings,
 * then asks Anthropic to generate a clean canonical name for each
 * cluster. The public search overlay and the admin Dynamic
 * Categories tab both read from this collection.
 *
 * Lifecycle:
 *   - 24h cron: deletes all non-locked rows for a batch, recomputes,
 *     inserts new clusters.
 *   - Admin: can rename a cluster's `canonicalName`, merge two
 *     clusters, or set `locked: true` to pin it from refresh.
 *   - First run after deploy: see scripts/backfillCategoryClusters.ts
 *     (backfills every active batch in one pass).
 *
 * Why dot product (not cosine): the FAQ embeddings are unit-normalized
 * at write time (see utils/ai/embeddings.ts → `normalize: true`),
 * so dot product IS cosine similarity. We use the same metric the
 * Atlas Vector Search index uses, so cluster results match what
 * users actually see as "similar" in search.
 */

import mongoose, { Schema as MongooseSchema, Types, type Document } from 'mongoose';

export interface ICategoryCluster extends Document {
  batchId: Types.ObjectId;

  /**
   * The cleaned-up canonical name for this cluster. Initially
   * generated by Anthropic from the member aliases; admins can
   * rename via the dashboard. Stable across refreshes unless the
   * cluster is unlocked — in which case the next refresh may pick
   * a different name.
   */
  canonicalName: string;

  /**
   * Raw category strings that this cluster represents. Each alias
   * is a `FAQ.category` value seen in the wild (e.g. "NOC",
   * "NOC (No Objection Certificate)"). Used to (a) reverse-map a
   * FAQ's category to its cluster, and (b) render the "members"
   * list in the admin tab.
   */
  aliases: string[];

  /**
   * Sum of FAQ counts across all aliases. Recomputed on every
   * refresh from the live FAQ collection. The cluster with the
   * highest `faqCount` is treated as the "head" cluster and gets
   * its alias name used as the canonical name fallback if the AI
   * naming step fails.
   */
  faqCount: number;

  /**
   * Centroid of the member alias embeddings (averaged and re-
   * normalized). Stored so the next refresh can do an O(1) centroid-
   * to-centroid similarity check against existing clusters before
   * deciding whether to re-cluster from scratch.
   */
  centroid: number[];

  /**
   * Set by an admin from the Dynamic Categories tab. When true, the
   * 24h refresh MUST NOT delete, rename, or merge this cluster.
   * Used when an admin has already curated the canonical name and
   * doesn't want the AI to clobber their work.
   */
  locked: boolean;

  /**
   * Set when this cluster was created (or last touched) by the
   * 24h refresh. The admin tab shows this to surface "stale"
   * clusters — anything older than 7 days probably needs attention.
   */
  lastRefreshedAt: Date;

  /**
   * When true, this row was renamed by an admin. The refresh
   * preserves `canonicalName` (and any merge targets) but is
   * allowed to re-cluster the aliases.
   */
  editedByAdmin: boolean;

  createdAt: Date;
  updatedAt: Date;
}

const categoryClusterSchema = new MongooseSchema<ICategoryCluster>(
  {
    batchId: {
      type: MongooseSchema.Types.ObjectId,
      ref: 'Batch',
      required: true,
      index: true,
    },
    canonicalName: { type: String, required: true, trim: true, maxlength: 120 },
    aliases: {
      type: [String],
      required: true,
      validate: {
        // Every cluster must have at least one alias — otherwise
        // it's just an empty bucket and should be deleted.
        validator: (v: string[]) => Array.isArray(v) && v.length > 0,
        message: 'A cluster must have at least one alias.',
      },
    },
    faqCount: { type: Number, required: true, default: 0, min: 0 },
    centroid: { type: [Number], default: [] },
    locked: { type: Boolean, default: false, index: true },
    lastRefreshedAt: { type: Date, default: Date.now, index: true },
    editedByAdmin: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// "Show me the top clusters for program X, most FAQs first" — the
// admin tab and the search-overlay pill list both hit this.
categoryClusterSchema.index({ batchId: 1, faqCount: -1 });

// "Reverse-map a FAQ's category string to its cluster for program X"
// — InteractiveSearchOverlay's pills call this on every search.
categoryClusterSchema.index({ batchId: 1, aliases: 1 });

export default mongoose.model<ICategoryCluster>(
  'CategoryCluster',
  categoryClusterSchema,
  'yaksha_category_clusters'
);
