import mongoose, { Document, Schema as MongooseSchema, Types } from 'mongoose';

/**
 * SupportCategory — the dynamic schema for a Session Support category.
 *
 * Each category owns:
 *   - a checklist (`steps`) shown to the user before they submit
 *   - a list of custom context fields (`fields`) the user must fill in
 *   - admin-side metadata (label, icon, order, active flag)
 *
 * Replaces the role of the older AttendanceGuidance model — that
 * model is now read by no one (kept in the codebase for one release
 * before cleanup).
 *
 * Storage shape for `fields` is a subdocument list. Soft-delete via
 * `archived: true`; archived fields are NOT rendered for input on
 * new submissions but their values are still readable on historical
 * tickets (because the ticket stores `{key, label, value}` triples).
 */

export type SupportFieldType = 'text' | 'textarea' | 'number' | 'date' | 'boolean' | 'dropdown';

export const SUPPORT_FIELD_TYPES: SupportFieldType[] = [
  'text', 'textarea', 'number', 'date', 'boolean', 'dropdown',
];

export const SUPPORT_ICON_KEYS = [
  'wifi', 'camera', 'mic', 'device', 'power', 'generic',
] as const;
export type SupportIconKey = typeof SUPPORT_ICON_KEYS[number];
// ─── Subdocuments ────────────────────────────────────────────────────────────

export interface IContextFieldOption {
  value: string;
  label: string;
}

export interface IContextField {
  _id?: Types.ObjectId;            // auto-generated by Mongoose
  /** Machine-readable key. Immutable after first save. */
  key: string;
  label: string;
  type: SupportFieldType;
  required: boolean;
  placeholder: string;
  helpText: string;
  /** For `dropdown` only. At least one entry when type === 'dropdown'. */
  options: IContextFieldOption[];
  displayOrder: number;
  archived: boolean;
  archivedAt: Date | null;
}

// ─── Document ───────────────────────────────────────────────────────────────

export interface ISupportCategory extends Document {
  /**
   * v1.69 — Phase 9: program scoping. null = global category
   * available to every program; non-null = per-program override.
   * When the migration runs, every existing category becomes
   * a global default (batchId: null). New categories are
   * created via the admin UI with a per-program batchId.
   */
  batchId: Types.ObjectId | null;
  /** Stable kebab-case key — e.g. 'internet', 'device', 'stipend-issue'. Unique. */
  issueType: string;
  label: string;
  shortLabel: string;
  description: string;
  iconKey: SupportIconKey;
  steps: string[];
  fields: IContextField[];
  isActive: boolean;
  displayOrder: number;
  createdBy: Types.ObjectId | null;
  createdAt: Date;
  updatedAt: Date;
}

// ─── Sub-schemas ────────────────────────────────────────────────────────────

const optionSubSchema = new MongooseSchema<IContextFieldOption>(
  {
    value: { type: String, required: true, trim: true, maxlength: 80 },
    label: { type: String, required: true, trim: true, maxlength: 120 },
  },
  { _id: false },
);

const fieldSubSchema = new MongooseSchema<IContextField>(
  {
    key: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      maxlength: 60,
      match: [/^[a-z0-9][a-z0-9-]*$/, 'key must be kebab-case (a-z, 0-9, dash)'],
    },
    label:        { type: String, required: true, trim: true, maxlength: 120 },
    type:         { type: String, enum: SUPPORT_FIELD_TYPES, required: true },
    required:     { type: Boolean, default: false },
    placeholder:  { type: String, default: '', maxlength: 200 },
    helpText:     { type: String, default: '', maxlength: 500 },
    options:      { type: [optionSubSchema], default: [] },
    displayOrder: { type: Number, default: 0 },
    archived:     { type: Boolean, default: false },
    archivedAt:   { type: Date, default: null },
  },
  { _id: true },
);

// ─── Schema ─────────────────────────────────────────────────────────────────

const supportCategorySchema = new MongooseSchema<ISupportCategory>(
  {
    // v1.69 — Phase 9: per-program scoping.
    batchId: {
      type: MongooseSchema.Types.ObjectId,
      ref: 'Batch',
      default: null,
      index: true,
    },
    issueType: {
      type: String,
      required: true,
      unique: true, // legacy global uniqueness — Phase 9+ relies on (batchId, issueType)
      trim: true,
      lowercase: true,
      maxlength: 60,
      match: [/^[a-z0-9][a-z0-9-]*$/, 'issueType must be kebab-case (a-z, 0-9, dash)'],
    },
    label:        { type: String, required: true, trim: true, maxlength: 120 },
    shortLabel:   { type: String, required: true, trim: true, maxlength: 40 },
    description:  { type: String, default: '', maxlength: 1000 },
    iconKey:      {
      type: String,
      enum: SUPPORT_ICON_KEYS as readonly SupportIconKey[],
      default: 'generic',
    },
    steps:        { type: [String], default: [] },
    fields:       { type: [fieldSubSchema], default: [] },
    isActive:     { type: Boolean, default: true, index: true },
    displayOrder: { type: Number, default: 0 },
    createdBy:    { type: MongooseSchema.Types.ObjectId, ref: 'User', default: null },
  },
  { timestamps: true },
);

// v1.69 — Phase 9: per-program uniqueness. A (batchId, issueType)
// pair is unique; a null batchId represents the global default.
// Allows a single kebab-case key to be reused across programs
// when the meaning diverges (e.g. program A has a 'device' issue
// type with different steps than program B).
supportCategorySchema.index(
  { batchId: 1, issueType: 1 },
  { unique: true, partialFilterExpression: { issueType: { $type: 'string' } } }
);

// "Active categories for this program, ordered for the picker"
// — the public listUsers endpoint uses this with the active
// program's batchId. The (batchId, isActive, displayOrder)
// index covers both the per-program picker and the fallback
// global-list (when batchId=null).
supportCategorySchema.index({ batchId: 1, isActive: 1, displayOrder: 1 });

// "All categories, ordered" — admin schema editor
supportCategorySchema.index({ displayOrder: 1 });

export default mongoose.model<ISupportCategory>(
  'SupportCategory',
  supportCategorySchema,
  'yaksha_faq_support_categories',
);
